spring.application.name=fleetmanager

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:fleetdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola de H2 para ver los datos en http://localhost:8080/h2-console
spring.h2.console.enabled=true

# JPA y Hibernate
# create-drop: Crea el esquema al iniciar y borra al cerrar
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANTE: Ejecutar data.sql o import.sql DESPUES de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always